config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('', include('qanda.urls', namespace='qanda')),
]

qanda/urls.py
from django.urls import path
from . import views

app_name = 'qanda'

urlpatterns = [
    path('ask', views.AskQuestionView.as_view(), name='ask'),
    path('q/<int:pk>', views.QuestionDetailView.as_view(), name='question_detail'),
    path('q/<int:pk>/answer', views.CreateAnswerView.as_view(),
         name='answer_question'),
    path('q/<int:pk>/accept', views.UpdateAnswerAcceptance.as_view(),
         name='update_answer_acceptance'),
    path('daily/<int:year>/<int:month>/<int:day>', views.DailyQuestionList.as_view(),
         name='daily_questions'),
    path('', views.TodayQuestionList.as_view(), name='home')
]

user/urls.py
from django.urls import path

from django.contrib.auth import urls, views as auth_views
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

qanda/models.py
from django.conf import settings
from django.urls.base import reverse
from django.db import models

# Create your models here.


class Question(models.Model):
    title = models.CharField(max_length=140)
    question = models.TextField()
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'qanda:question_detail',
            kwargs={'pk': self.id}
        )

    def can_accept_answers(self, user):
        return user == self.user


class Answer(models.Model):
    answer = models.TextField()
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    created = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(
        to=Question,
        on_delete=models.CASCADE
    )
    accepted = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.answer

user/models.py
from django.db import models

# Create your models here.

qanda/forms.py
from django import forms
from django.contrib.auth import get_user_model

from . import models


class QuestionForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True
    )

    class Meta:
        model = models.Question
        fields = ['title', 'question', 'user', ]


class AnswerForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,
    )

    question = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=models.Question.objects.all(),
        disabled=True,
    )

    class Meta:
        model = models.Answer
        fields = ['answer', 'user', 'question', ]


class AnswerAcceptanceForm(forms.ModelForm):
    accepted = forms.BooleanField(
        widget=forms.HiddenInput,
        required=False
    )

    class Meta:
        model = models.Answer
        fields = ['accepted', ]

qanda/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, UpdateView, DayArchiveView, RedirectView
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.utils import timezone
from . import models
from . import forms
# Create your views here.


class AskQuestionView(LoginRequiredMixin, CreateView):
    form_class = forms.QuestionForm
    template_name = 'qanda/ask.html'

    def get_initial(self):
        return {
            'user': self.request.user.id
        }

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == 'SAVE':
            # save and rediret as usual
            return super().form_valid(form)

        elif action == 'PREVIEW':
            preview = models.Question(
                question=form.cleaned_data['question'],
                title=form.cleaned_data['title']
            )
            ctx = self.get_context_data(preview=preview)
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()


class QuestionDetailView(DetailView):
    model = models.Question
    template_name = 'qanda/question_detail.html'

    ACCEPT_FORM = forms.AnswerAcceptanceForm(initial={'accepted': True})
    REJECT_FORM = forms.AnswerAcceptanceForm(initial={'accepted': False})

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update({
            'answer_form': forms.AnswerForm(initial={
                'user': self.request.user.id,
                'question': self.object.id,
            })
        })
        if self.object.can_accept_answers(self.request.user):
            ctx.update({
                'accept_form': self.ACCEPT_FORM,
                'reject_form': self.REJECT_FORM,
            })
        return ctx


class CreateAnswerView(LoginRequiredMixin, CreateView):
    form_class = forms.AnswerForm
    template_name = 'qanda/create_answer.html'

    def get_initial(self):
        return {
            'question': self.get_question().id,
            'user': self.request.user.id
        }

    def get_context_data(self, **kwargs):
        return super().get_context_data(question=self.get_question(), **kwargs)

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == 'SAVE':
            # save and redirect as usual
            return super().form_valid(form)
        elif action == 'PREVIEW':
            ctx = self.get_context_data(
                preview=form.cleaned_data['answer']
            )
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()

    def get_question(self):
        return models.Question.objects.get(pk=self.kwargs['pk'])


class UpdateAnswerAcceptance(LoginRequiredMixin, UpdateView):
    form_class = forms.AnswerAcceptanceForm
    queryset = models.Answer.objects.all()

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_invalid(self, form):
        return HttpResponseRedirect(
            redirect_to=self.object.question.get_absolute_url()
        )


class DailyQuestionList(DayArchiveView):
    queryset = models.Question.objects.all()
    date_field = 'created'
    month_format = '%m'
    allow_empty = True

    template_name = 'qanda/question_archive_day.html'


class TodayQuestionList(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        today = timezone.now()
        return reverse(
            'qanda:daily_questions',
            kwargs={
                'day': today.day,
                'month': today.month,
                'year': today.year
            }
        )

user/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


class RegisterView(CreateView):
    template_name = 'user/register.html'
    form_class = UserCreationForm

qanda/templates/qanda/ask.html
{% extends "base.html" %}
{% load markdownify %}
{% load crispy_forms_tags %}

{% block title %}
  Ask a question
{% endblock title %}

{% block body %}
  <div class="col-md-12">
    <h1>Ask a question</h1>
    {% if preview %}
      <div class="card question-preview">
        <div class="card-header">
          Question Preview
        </div>
        <div class="card-body">
          <div class="card-title">{{ preview.title }}</div>
          {{ preview.question|markdownify }}
        </div>
      </div>
    {% endif %}

    <form method="post">
      {{ form|crispy }}
      {% csrf_token %}
      <button type="submit" name='action' value="PREVIEW" class="btn btn-primary">
        Preview
      </button>
      <button type="submit" name='action' value="SAVE" class="btn btn-primary">
        Ask!
      </button>
    </form>
  </div>
{% endblock body %}

qanda/templates/qanda/common/display_question.html
{% load markdownify %}
<div class="question">
  <div class="meta col-sm-12 mb-4">
    <h1>{{ question.title }}</h1>
    Asked by {{ question.user }} on {{ question.created }}
  </div>
  <div class="body col-sm-12 mb-4">
    {{ question.question|markdownify }}
  </div>
</div>

qanda/templates/qanda/common/list_answers.html
{% load markdownify %}
<h3>Answers</h3>
<ul class="list-unsyled answers">
  {% for answer in question.answer_set.all %}
    <li class="answer row">
      <div class="col-sm-3 col-md-2 text-center">

        {% if answer.accepted %}
          <span class="badge badge-pill badge-success">Accepted</span>
        {% endif %}

        {% if answer.accepted and reject_form %}
          <form action="{% url 'qanda:update_answer_acceptance' pk=answer.id %}" method="post">
            {% csrf_token %}
            {{ reject_form }}
            <button type="submit" class="btn btn-link">
              <i class="fa fa-times" aria-hidden="true"></i>
              Reject
            </button>
          </form>

        {% elif accept_form %}
        <form action="{% url 'qanda:update_answer_acceptance' pk=answer.id %}" method="post">
          {% csrf_token %}
          {{ accept_form }}
          <button class="btn btn-link" type="submit" title="Accept answer">
            <i class="fa fa-check-circle" aria-hidden="true"></i>
            Accept
          </button>
        </form>
        {% endif %}

      </div>
      <div class="col-sm-9 col-md-10">
        <div class="body">
          {{ answer.answer|markdownify }}
          <div class="meta font-weight-light mt-3 mb-5">
            Answer by {{ answer.user }} on {{ answer.created }}
          </div>
        </div>
      </div>
    </li>
  {% empty %}
    <li class="answer">No answer yet!</li>
  {% endfor %}
</ul>

qanda/templates/qanda/common/question_post_answer.html
{% load crispy_forms_tags %}
<div class="col-sm-12">
  <h3>Post your answers</h3>
  <form action="{% url 'qanda:answer_question' pk=question.id %}" method="POST">
    {{ answer_form|crispy }}
    {% csrf_token %}
    <button type="submit" name="action" value="PREVIEW" class="btn btn-primary">
      Preview
    </button>
    <button type="submit" name="action" value="SAVE" class="btn btn-primary">
      Answer
    </button>
  </form>
</div>

qanda/templates/qanda/create_answer.html
{% extends "base.html" %}
{% load markdownify %}

{% block title %}
  {{ question.title }} - {{ block.super }}
{% endblock title %}

{% block body %}
  {% include "qanda/common/display_question.html" %}
  {% if preview %}
    <div class="card question-preview">
      <div class="card-header">
        Answer Preview
      </div>
      <div class="card-body">
        {{ preview|markdownify }}
      </div>
    </div>
  {% endif %}
  {% include "qanda/common/question_post_answer.html" with answer_form=form %}
{% endblock body %}

qanda/templates/qanda/question_archive_day.html
{% extends "base.html" %}

{% block title %}
  Question on {{ day }}
{% endblock title %}

{% block body %}
  <div class="col-sm-12">
    <h1>Highest Voted Questions of {{ day }}</h1>
    <ul class="mt-5">
      {% for question in object_list %}
        <li class="mb-4">
          {{ question.votes }}
          <a href="{{ question.get_absolute_url }}">
            {{ question }}
          </a>
          by
          {{ question.user }} on
          {{ question.created }}
        </li>
      {% empty %}
        <li><strong>Hmm.. Everyone thinks they know everything today</strong></li>
      {% endfor %}
    </ul>
    {% if previous_day %}
      <a href="{% url 'qanda:daily_questions' year=previous_day.year month=previous_day.month day=previous_day.day %}">
        << Previous Day
      </a>
    {% endif %}
    {% if next_day %}
      <a href="{% url 'qanda:daily_questions' year=next_day.year month=next_day.month day=next_day.day %}">
        Next Day >>
      </a>
    {% endif %}
  </div>
{% endblock body %}

qanda/templates/qanda/question_detail.html
{% extends "base.html" %}

{% block title %}
  {{ question.title }} - {{ block.super }}
{% endblock title %}

{% block body %}
  {% include "qanda/common/display_question.html" %}
  {% include "qanda/common/list_answers.html" %}
  {% if user.is_authenticated %}
    {% include "qanda/common/question_post_answer.html" %}
  {% else %}
    <div>
      Login to post answers.
    </div>
  {% endif %}
{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'base.css' %}">

  <title>
    {% block title %}
      Answerly
    {% endblock title %}
  </title>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <a href="{% url 'qanda:home' %}" class="navbar-brand">Answerly</a>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url 'qanda:ask' %}" class="nav-link">
            Ask
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'qanda:home' %}" class="nav-link">
            Todays Hot Questions
          </a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'user:logout' %}" class="nav-link">
              Logout
            </a>
          </li>
        {% else %}
          <li class="nav-item">
            <a href="{% url 'user:login' %}" class="nav-link">
              Login
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'user:register' %}" class="nav-link">
              Register
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <div class="container">
    {% block body %} {% endblock body %}
  </div>
</body>
</html>

user/templates/user/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  Register - {{ block.super }}
{% endblock title %}

{% block body %}
  <div class="col-sm-12">
    <h1>Register for Answerly</h1>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">
        Register
      </button>
    </form>
  </div>
{% endblock body %}